apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wedge-app-splash
  labels:
    app.kubernetes.io/name: wedge-app-splash
    app.kubernetes.io/part-of: wedge-app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - wedge-app.reeves.racing
      secretName: wedge-app-splash-tls
  rules:
    - host: wedge-app.reeves.racing
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wedge-app-splash
                port:
                  number: 80
