apiVersion: v1
kind: Service
metadata:
  name: wedge-app-splash
  labels:
    app.kubernetes.io/name: wedge-app-splash
    app.kubernetes.io/part-of: wedge-app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: wedge-app-splash
  ports:
    - name: http
      port: 80
      targetPort: http
