apiVersion: apps/v1
kind: Deployment
metadata:
  name: wedge-app
  namespace: wedge-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wedge-app
  template:
    metadata:
      labels:
        app: wedge-app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          image: nginx:1.29
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
